name: requester
description: Provides a middlware API for package:http
version: 1.0.0
homepage: https://github.com/johnpryan/requester
author: John Ryan <john.p.ryan4@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.1
